### ISSUE TITLE
Excessive memory usage for CORE profile on integrated GPU (Windows OS)

### ISSUE THREAD

**Issue by DrunkyBard** [LWJGLX/lwjgl3-awt#48]
Hi,

I tried to run [Core32Test ](https://github.com/LWJGLX/lwjgl3-awt/blob/main/test/org/lwjgl/opengl/awt/Core32Test.java) on Windows OS on integrated GPU and noticed excessive memory usage on window resizing. Eventually application stops rendering process and crashes with MEMORY_ACCESS_VIOLATION exception when user continues resizing target window.
Everything is fine on Compatibility profile for integrated GPU. Also Core profile test app works correctly on dedicated GPU.

I managed to reproduce such behaviour on 2 machines with integrated GPU, they had Intel UHD graphics on board. 
Idk if it is useful info but first machine had 27.20.100.8729 9/11/2020 driver, second one — 27.20.100.9168 1/8/2021.

Core profile works correctly on the third machine with Linux OS on Intel UHD graphics 620 integrated GPU.

Is it possible that there is a bug in GPU driver or there might be some workaround to avoid enormous memory consumption on Windows for integrated GPU?

**Comment by SWinxy** [comment]
The OpenGL tests have a lot of memory leaks, but I don't think that's the issue here, as the tests don't continually (to my knowledge) leak memory.

@DrunkyBard do all the OpenGL tests cause this issue? Have you tried the Vulkan one ([`SimpleDemo`](https://github.com/LWJGLX/lwjgl3-awt/blob/main/test/org/lwjgl/vulkan/awt/SimpleDemo.java))? How many times do you have to resize the window does it take to crash? My CPU doesn't have integrated graphics so I can't test it.

**Comment by DrunkyBard** [comment]
Other tests are ok since they use compatibility mode. I didn't try the Vulkan example. 
I resize the window constantly as soon as application started. Application crashes within a minute in that case.

**Comment by SWinxy** [comment]
Do you know what is causing the crash? The logs have a stack trace which is sometimes hard to see. What's the problematic frame, and what's the stacktrace?

**Comment by DrunkyBard** [comment]
Here is the dump file generated after the crash:
[CORE_PROFILE_CRASH_DUMP.txt](https://github.com/LWJGLX/lwjgl3-awt/files/7101859/CORE_PROFILE_CRASH_DUMP.txt)

**Comment by SWinxy** [comment]
Done some digging and it appears that `ReleaseDC()` in `User32` or `wglMakeCurrent()` in `WGL` may be the cause. I can't know what the exact stack trace is, as it'd been inlined by the JIT. I'm not at a Windows computer for the next few days, so could you try to run it w/o the JIT as a VM option (`-Djava.compiler=NONE`)?

**Comment by DrunkyBard** [comment]
I've tested with given VM options - still the same result and same stacktrace

**Comment by SWinxy** [comment]
Hm... Odd. I can't seem to reproduce the issue. @httpdigest you know about OpenGL, any thoughts?
